# Generated by Django 3.2.5 on 2021-09-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('plan_id', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('interval', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'SubscriptionPlan',
                'verbose_name_plural': 'SubscriptionPlans',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_stripe_customer', models.BooleanField(default=False, verbose_name='StripeCustomer')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Subscribed User')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='Subscription Start')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='Subscription End')),
                ('subscription_interval', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subscription Interval')),
                ('subscription_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2, verbose_name='Subscription status')),
                ('is_free', models.BooleanField(default=False, verbose_name='Free Access')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Trial Access')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Trial End')),
                ('subscription_id', models.CharField(blank=True, max_length=30, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plan', to='payments.subscriptionplan')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserSubscription',
                'verbose_name_plural': 'UserSubscriptions',
            },
        ),
    ]
