# Generated by Django 3.2.5 on 2021-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscriptionplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='interval_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='cycle for billing'),
        ),
    ]
