# Generated by Django 3.2.5 on 2021-08-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='compliance',
            field=models.IntegerField(blank=True, choices=[(1, 'Training'), (2, 'Others')], null=True, verbose_name='Compliance'),
        ),
    ]
