# Generated by Django 3.2.5 on 2021-07-15 07:59

import accounts.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Image')),
                ('company', models.CharField(blank=True, max_length=120, null=True, verbose_name='Company name')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('user_role', models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2, verbose_name='User Role')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('is_admin_approved', models.BooleanField(default=False, verbose_name='Admin Approval')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUser')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ['id'],
                'index_together': {('email', 'phone_number', 'updated_at')},
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
                ('all_delete_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('expired_at', models.DateTimeField(verbose_name='Expired At')),
                ('is_used', models.BooleanField(default=False, verbose_name='IsUsed')),
                ('verification_type', models.IntegerField(choices=[(1, 'Verifiy Email'), (2, 'Forgot Password'), (3, 'Other')], verbose_name='Verification Type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_token', to='accounts.user')),
            ],
            options={
                'verbose_name': 'AccountVerification',
            },
        ),
    ]
