# Generated by Django 3.2.5 on 2021-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('questions', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Radio Button'), (2, 'Text'), (3, 'Radio and Text both'), (4, 'Drop Down'), (5, 'Two Drop Down'), (6, 'Three Drop Down')], null=True, verbose_name='Type of answers')),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Export'), (2, 'Import'), (3, 'Risk AAssessment'), (4, 'Training'), (5, 'Product Certification and Validation'), (6, 'Asia Market Services')], null=True, verbose_name='Category of Compliance')),
                ('subcategory', models.IntegerField(blank=True, choices=[(1, 'Export Product'), (2, 'Export Services'), (3, 'Export Both')], null=True, verbose_name='Subcategory of Compliance')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
                'index_together': {('created_at', 'updated_at')},
            },
        ),
    ]
