# Generated by Django 3.2.5 on 2021-07-23 09:58

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('accounts', '0002_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Export'), (2, 'Import'), (3, 'Risk Assessment'), (4, 'Training'), (5, 'Product Certification and Validation'), (6, 'Asia Market Services')], null=True, verbose_name='Category of Compliance'),
        ),
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('question_answer', models.JSONField(blank=True, null=True, verbose_name='Questionnaire_id and Answers')),
                ('compliance', models.IntegerField(blank=True, choices=[(1, 'Export'), (2, 'Import'), (3, 'Risk Assessment'), (4, 'Training'), (5, 'Product Certification and Validation'), (6, 'Asia Market Services')], null=True, verbose_name='Compliance')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('meet_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meeting Link')),
                ('state', models.IntegerField(choices=[(1, 'created'), (2, 'cancel'), (3, 'payment on hold'), (4, 'completed')], default=1, verbose_name='State')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('complaince_challenge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pdf file')),
                ('admin_response', models.IntegerField(blank=True, choices=[(1, 'Meeting accepted by Admin'), (2, 'Meeting rejected by Admin'), (3, 'Meeting pending by Admin'), (4, 'Meeting rescheduled by Admin')], null=True, verbose_name='admin response')),
                ('consultant_feedback', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), blank=True, null=True, size=None)),
                ('payment_via', models.IntegerField(blank=True, choices=[(1, 'Subscription'), (2, 'Card'), (3, 'Invoice request')], null=True, verbose_name='Payment Methods')),
                ('cancellation_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Id')),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Intent Id')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_meeting', to='admins.timeslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
                'index_together': {('created_at', 'updated_at')},
            },
        ),
    ]
