# Generated by Django 3.2.5 on 2021-08-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemeeting',
            name='user_response',
            field=models.IntegerField(blank=True, choices=[(1, 'Meeting accepted by user'), (2, 'Meeting rejected by user'), (3, 'Meeting pending by user')], null=True, verbose_name='user response'),
        ),
    ]
