# Generated by Django 3.2.5 on 2021-08-25 07:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_devicemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='region')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
            ],
        ),
        migrations.AddField(
            model_name='schedulemeeting',
            name='region_country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='subcategory',
            field=models.IntegerField(blank=True, choices=[(1, 'Export Product'), (2, 'Export Services'), (3, 'Export Both'), (4, 'China Market Liaison'), (5, 'China Supply Chain Support'), (6, 'China Market Compliance'), (7, 'India Market Liaison')], null=True, verbose_name='Subcategory of Compliance'),
        ),
    ]
